export const ACCOUNT_UI = {
  accountNewReport: "Nuovo report",
  accountSearchVehicle: "Cerca un veicolo per targa o VIN",
  accountSearchType: "Tipo di ricerca",
  accountPlate: "Targa",
  accountVIN: "VIN",
  accountPlateNumber: "Targa italiana",
  accountVINNumber: "Numero di telaio (VIN)",
  accountVINCharacters: "17 caratteri alfanumerici",
  accountReportCost: "Costo del report",
  accountOneCreditFromAccount: "1 credito verrà scalato dal tuo account.",
  accountCreditsRemaining: "Crediti rimanenti: {credits}",
  accountCancel: "Annulla",
  actionGenerate: "Genera report",
  loadingGenerating: "Generazione...",
  accountGenerationStarting: "🚀 Avvio elaborazione...",
  accountCheckingCredits: "💳 Verifica crediti...",
  accountCreditDeducted: "✅ Credito addebitato",
  accountCallingAPI: "📡 Interrogazione banche dati...",
  accountAPISuccess: "✅ Dati veicolo recuperati",
  accountAnalyzing: "🧠 Analisi intelligente in corso...",
  accountAnalysisComplete: "✅ Analisi completata",
  accountGeneratingPDF: "📄 Generazione PDF...",
  accountPDFGenerated: "✅ PDF generato",
  accountSendingEmail: "📧 Invio email in corso...",
  accountEmailSent: "✅ Email inviata",
  accountReportSuccess: "🎉 Report generato con successo!",
  accountReportGeneratedSuccess: "Report generato con successo!",
  accountReportAddedToAccount: "Il tuo report è stato aggiunto al tuo account.",
  accountViewMyReport: "Visualizza il mio report",
  accountMyReports: "I miei report",
  accountLoadingReports: "Caricamento report...",
  accountErrorLoading: "Errore durante il caricamento",
  accountRetry: "Riprova",
  accountRefresh: "Aggiorna",
  accountNoReports: "Nessun report generato",
  accountGenerateFirst: "Genera il tuo primo report dal pulsante sopra.",
  accountDownloading: "Download...",
  accountDownloaded: "Scaricato!",
  accountErrorDownload: "Errore",
  actionView: "Visualizza",
  tooltipReportHint: "I report rimangono disponibili nel tuo account.",
} as const;
